adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    path("", adminapp.admin_main, name="admin_main"),
    path("users/create/", adminapp.ArtShopUserCreateView.as_view(), name="user_create"),
    path("users/read/", adminapp.UsersListView.as_view(), name="users"),
    path("users/update/<int:pk>/", adminapp.ArtShopUserUpdateView.as_view(), name="user_update"),
    path("users/delete/<int:pk>/", adminapp.ArtShopUserDeleteView.as_view(), name="user_delete"),
    path("categories/create/", adminapp.ArtCategoryCreateView.as_view(), name="category_create"),
    path("categories/read/", adminapp.categories, name="categories"),
    path("categories/update/<int:pk>/", adminapp.ArtCategoryUpdateView.as_view(), name="category_update"),
    path("categories/delete/<int:pk>/", adminapp.ArtCategoryDeleteView.as_view(), name="category_delete"),
    path("products/create/category/<int:pk>/", adminapp.product_create, name="product_create"),
    path("products/read/category/<int:pk>/", adminapp.products, name="products"),
    path("products/read/<int:pk>", adminapp.ArtObjectDetailView.as_view(), name="product_read"),
    path("products/update/<int:pk>/", adminapp.product_update, name="product_update"),
    path("products/delete/<int:pk>/", adminapp.ArtObjectDeleteView.as_view(), name="product_delete"),
]

artshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("register/", authapp.register, name="register"),
    path("edit/", authapp.edit, name="edit"),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

from .apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
    path("edit/<int:pk>/<int:quantity>/", basketapp.basket_edit, name="edit"),
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", mainapp.products, name="index"),
    path("products/<int:pk>/", mainapp.products, name="products"),
    path("products/<int:pk>/page/<int:page>", mainapp.products, name="page"),
    path("product/<int:pk>/", mainapp.product, name="product"),
    path('catalog/', mainapp.catalog, name='catalog'),
    path('contacts/', mainapp.contacts, name='contacts'),
]

mainapp/models.py
from django.db import models

# Create your models here.
class ArtCategory(models.Model):
    name = models.CharField(verbose_name="name", max_length=64, unique=True)
    description = models.TextField(verbose_name="description", blank=True)
    is_active = models.BooleanField(verbose_name="category is active", default=True)

    def __str__(self):
        return self.name

class ArtObject(models.Model):
    category = models.ForeignKey(ArtCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="artobject name", max_length=128)
    image = models.ImageField(upload_to="art_images", blank=True)
    artist = models.CharField(verbose_name="author", max_length=60, blank=True)
    description = models.TextField(verbose_name="artobject description", blank=True)
    price = models.DecimalField(verbose_name="price", max_digits=12, decimal_places=2, default=0)
    location = models.CharField(verbose_name="location", max_length=128)
    is_active = models.BooleanField(verbose_name="art object is active", default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="phone number")
    email = models.EmailField(max_length=254, verbose_name="email")
    city = models.CharField(max_length=128, verbose_name="city")
    address = models.CharField(max_length=254, verbose_name="address")

    def __str__(self):
        return f"{self.pk} {self.email}"
    

mainapp/views.py
from django.conf import settings
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
import datetime
from .models import Contact, ArtObject, ArtCategory
from basketapp.models import Basket
import random

# Create your views here.

def main(request):
    title = "главная",
    
    content = {"title": title}
    return render(request, "mainapp/index.html", content)

def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []

def get_hot_product():
    products = ArtObject.objects.filter(is_active=True, category__is_active=True)
    return random.sample(list(products), 1)[0]

def products(request, pk=None, page=1):
    title = "Картины"

    basket = get_basket(request.user)
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    if pk is not None:
        if pk == 0:
            products = ArtObject.objects.filter(is_active=True, category__is_active=True).order_by("price")
            category = {"pk": 0, "name": "all"}
        else:
            category = get_object_or_404(ArtCategory, pk=pk)
            products = ArtObject.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by("price")
        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)    
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        content = {
            "title": title, 
            "products": products_paginator, 
            "category": category, 
            "media_url": settings.MEDIA_URL,
            "basket": basket,
            }
        return render(request, "mainapp/products_list.html", content)
    products = ArtObject.objects.filter(is_active=True, category__is_active=True)[:3]
    content = {
        "title": title,
        "products": products,
        "media_url": settings.MEDIA_URL,
        "basket": basket,
    }
    if pk:
        print(f"User select category: {pk}")
    return render(request, "mainapp/products.html", content)

def contacts(request):
    title = "о нас"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contacts.html", content)

def catalog(request):
    title = "Каталог"
    links_menu = ArtCategory.objects.all()
    basket = get_basket(request.user)
    hot_product = get_hot_product()
    content = {
        "title": title, 
        "links_menu": links_menu,
        "hot_product": hot_product,
        "media_url": settings.MEDIA_URL,
        "basket": basket,
        }
    return render(request, "mainapp/catalog.html", content)

def product(request, pk):
    title = "продукты"
    content = {
        "title": title,
        "product": get_object_or_404(ArtObject, pk=pk),
        "basket": get_basket(request.user),
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/product.html", content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
{% load static %}

<ul class="links-menu">
    <li>
      <a href="{% url 'products:products' pk=0 %}" 
      class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">
        All
      </a>
    </li>
    {% for link in links_menu %}
    <li>
      <a href="{% url 'products:products' link.pk %}" 
      class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}active{% endif %}">
          {{ link.name }}
      </a>
    </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_header1.html
{% load static %}

<div class="header1">
    <a class="logo" href="{% url 'main' %}"
      ><img src="{% static 'img/logo.png' %}" alt=""
    /></a>
    <div class="phone">
      <p><i class="fas fa-mobile-alt"></i> +7(495)122-33-22</p>
    </div>
    <div class="mail">
      <p><i class="far fa-envelope"></i> contact@flame.art</p>
    </div>
  </div>

mainapp/templates/mainapp/includes/inc_header2.html
{% load humanize %}

<div class="header2">
    <ul>
      <li><a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}">Home</a></li>
      <li><a href="{% url 'products:catalog' %}" class="{% if request.resolver_match.url_name == 'catalog' %}active{% endif %}">Catalog</a></li>
      <li><a href="{% url 'products:products' pk=0 %}" class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}">Art Objects</a></li>
      <li><a href="{% url 'products:contacts' %}" class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">Contacts</a></li>
      
      {% if user.is_authenticated %}
      <li>
        <a href="{% url 'auth:edit' %}">
          {{ user.first_name|default:'User' }}
        </a>
      </li>
      {% endif %}
      {% if user.is_superuser %}
        <li>
          <a href="{% url 'admin:users' %}">Admin site</a>
        </li>
      {% endif %}
      <li>
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'auth:login' %}">Login</a>
        {% endif %}
        </li>
        <li>
          <a href="{% url 'basket:view' %}" class="basket"><i class="fas fa-shopping-basket"></i>
          <span>
            {% if basket %} 
              {{ basket.0.total_price|stringformat:"d"|intcomma }} $ ({{ basket.0.total_quantity }} pcs) 
            {% endif %}
          </a>
        </li>
    </ul>
  </div>