artshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

from .apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
    path("edit/<int:pk>/<int:quantity>/", basketapp.basket_edit, name="edit"),
]

basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import ArtObject

# Create your models here.

class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="basket", on_delete=models.CASCADE)
    product = models.ForeignKey(ArtObject, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="quantity", default=0)
    add_datetime = models.DateTimeField(verbose_name="add time", auto_now_add=True)

    @property
    def product_cost(self):
        "return total cost of all art objects of this type"
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        "return total quantity for user"
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    @property
    def total_cost(self):
        "return total cost for user"
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

basketapp/views.py
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.contrib.auth.decorators import login_required
from basketapp.models import Basket
from mainapp.models import ArtObject
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string


@login_required
def basket(request):
    title = "basket"
    basket_items = Basket.objects.filter(user=request.user).order_by("product__category")
    content = {
        "title": title,
        "basket_items": basket_items,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "basketapp/basket.html", content)


@login_required
def basket_add(request, pk):
    if "login" in request.META.get("HTTP_REFERER"):
        return HttpResponseRedirect(reverse("products:product", args=[pk]))
    product = get_object_or_404(ArtObject, pk=pk)
    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        print(f"{pk} - {quantity}")
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity  = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_items = Basket.objects.filter(user=request.user).order_by("product__category")
        content = {
            "basket_items": basket_items,
            "media_url": settings.MEDIA_URL,
            }
        result = render_to_string("basketapp/includes/inc_basket_list.html", content)

        return JsonResponse({"result": result})

basketapp/templates/basketapp/includes/inc_basket_list.html
{% load static %}
{% load humanize %}


{% for item in basket_items %}
        <div class="basket-record">
            <img src="{{ media_url }}{{ item.product.image }}" alt="{{ item.product.artist }}">
            <span class="category-name">{{ item.product.category.name }}</span>
            <span class="product-name">{{ item.product.name }}</span>
            <span class="product-price">{{ item.product.price|stringformat:"d"|intcomma }}</span>
            <input type="number" name="{{ item.pk }}" min="0" value="{{ item.quantity }}">
            <span class="product-cost">{{ item.cost }}$</span>
            <button class="btn btn-round">
                <a href="{% url 'basket:remove' item.pk %}">Remove</a>
            </button>
        </div>
    
    {% endfor %}
    </div>
    {% if basket_items %}
        <div class="basket-summary">
            {{ basket_items.0.total_quantity }} goods total value of {{ basket_items.0.total_cost|stringformat:"d"|intcomma }}$ in your basket.
        </div>
    {% endif %}