adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    path("", adminapp.admin_main, name="admin_main"),
    path("users/create/", adminapp.ArtShopUserCreateView.as_view(), name="user_create"),
    path("users/read/", adminapp.UsersListView.as_view(), name="users"),
    path("users/update/<int:pk>/", adminapp.ArtShopUserUpdateView.as_view(), name="user_update"),
    path("users/delete/<int:pk>/", adminapp.ArtShopUserDeleteView.as_view(), name="user_delete"),
    path("categories/create/", adminapp.ArtCategoryCreateView.as_view(), name="category_create"),
    path("categories/read/", adminapp.categories, name="categories"),
    path("categories/update/<int:pk>/", adminapp.ArtCategoryUpdateView.as_view(), name="category_update"),
    path("categories/delete/<int:pk>/", adminapp.ArtCategoryDeleteView.as_view(), name="category_delete"),
    path("products/create/category/<int:pk>/", adminapp.product_create, name="product_create"),
    path("products/read/category/<int:pk>/", adminapp.products, name="products"),
    path("products/read/<int:pk>", adminapp.ArtObjectDetailView.as_view(), name="product_read"),
    path("products/update/<int:pk>/", adminapp.product_update, name="product_update"),
    path("products/delete/<int:pk>/", adminapp.ArtObjectDeleteView.as_view(), name="product_delete"),
]

artshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.forms import ArtShopUserEditForm
from authapp.models import ArtShopUser
from mainapp.models import ArtCategory, ArtObject

class ArtShopUserAdminEditForm(ArtShopUserEditForm):
    class Meta:
        model = ArtShopUser
        fields = "__all__"


class ArtCategoryEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = ArtCategory
        fields = "__all__"


class ArtObjectEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArtObjectEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = ArtObject
        fields = "__all__"

adminapp/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from adminapp.forms import ArtShopUserAdminEditForm, ArtCategoryEditForm, ArtObjectEditForm
from authapp.forms import ArtShopUserRegisterForm
from authapp.models import ArtShopUser
from mainapp.models import ArtObject, ArtCategory

# Create your views here.

@user_passes_test(lambda u: u.is_superuser)
def admin_main(request):
    response = redirect("admin:users")
    return response

class UsersListView(LoginRequiredMixin, ListView):
    model = ArtShopUser
    template_name = "adminapp/users.html"

class ArtShopUserCreateView(LoginRequiredMixin, CreateView):
    model = ArtShopUser
    template_name = "adminapp/user_update.html"
    success_url = reverse_lazy("admin:users")
    fields = "__all__"

class ArtShopUserUpdateView(LoginRequiredMixin, UpdateView):
    model = ArtShopUser
    template_name = "adminapp/user_update.html"
    success_url = reverse_lazy("admin:users")
    fields = "__all__"

class ArtShopUserDeleteView(LoginRequiredMixin, DeleteView):
    model = ArtCategory
    template_name = "adminapp/user_delete.html"
    success_url = reverse_lazy("admin:users")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = "adminsite/categories"
    categories_list = ArtCategory.objects.all()
    content = {
        "title": title,
        "objects": categories_list,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "adminapp/categories.html", content)

class ArtCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ArtCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"

class ArtCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ArtCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super(ArtCategoryUpdateView, self).get_context_data(**kwargs)
        context["title"] = "categories/edit"
        return context
        

class ArtCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ArtCategory
    template_name = "adminapp/category_delete.html"
    success_url = reverse_lazy("admin:categories")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = "adminsite/product"
    category = get_object_or_404(ArtCategory, pk=pk)
    products_list = ArtObject.objects.filter(category__pk=pk).order_by("name")
    content = {
        "title": title,
        "category": category,
        "objects": products_list,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "adminapp/products.html", content)

@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = "art object / creation"
    category = get_object_or_404(ArtCategory, pk=pk)

    if request.method == "POST":
        product_form = ArtObjectEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse("admin:products", args=[pk]))
    else:
        product_form = ArtObjectEditForm(initial={"category": category})

    content = {
        "title": title,
        "update_form": product_form,
        "category": category,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "adminapp/product_update.html", content)

@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = "art object / edit"
    edit_product = get_object_or_404(ArtObject, pk=pk)

    if request.method == "POST":
        edit_form = ArtObjectEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("admin:product_update", args=[edit_product.pk]))
    else:
        edit_form = ArtObjectEditForm(instance=edit_product)

    content = {
        "title": title,
        "update_form": edit_form,
        "category": edit_product.category,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "adminapp/product_update.html", content)


class ArtObjectDetailView(LoginRequiredMixin, DetailView):
    model = ArtObject
    template_name = "adminapp/product_read.html"



class ArtObjectDeleteView(LoginRequiredMixin, DeleteView):
    model = ArtObject
    template_name = "adminapp/product_delete.html"
    success_url = reverse_lazy("admin:products")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

adminapp/templates/adminapp/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}

</head>

<body>
    <div class="admin_container">
        <div class="h2 text-center head">
            Adminsite
        </div>
        {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
        {% endblock %}


        {% block content %}
        {% endblock %}

    </div>
</body>

</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="categories_list">
    <button class="new_category">
        <a href={% url 'admin:category_create' %}>New category</a>
    </button>

    {% for object in objects %}
    <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_actions">
            <button>
                <a href={% url 'admin:products' object.pk %}>ArtObjects of the category</a>
            </button>
            <button>
                <a href={% url 'admin:category_update' object.pk %}>Edit</a>
            </button>
            <button>
                <a href={% url 'admin:category_delete' object.pk %}>Delete</a>
            </button>
        </div>
        <div class="category_desc">
            {{ object.description|title }}
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="category_delete">
    Are you sure? <strong>{{ category_to_delete.name }}</strong>?
    <form action="{% url 'admin:category_delete' category_to_delete.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="delete">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin:categories' %}">cancel</a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="new_category_form">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="save">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:categories' %}">
            to categories list
        </a>
    </button>
</div>
{% endblock content %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="product_delete">
    Are you sure? <strong>{{ object.name }}</strong>?
    <form action="{% url 'admin:product_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="delete">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin:products' object.category.pk %}">
            cancel
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load humanize %}


{% block content %}
<div class="product_read">
    <div class="product_name">
        Art object<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
    <div class="summary">
        <b>Price</b>
        <p>{{ object.price|stringformat:"d"|intcomma }} $</p>
        <b>Quantity</b>
        <p>{{ object.quantity }}</p>
        <b>In catalog</b>
        <p>{% if object.is_active %}yes{% else %}no{% endif %}</p>
        <p>
            <button>
                <a href={% url 'admin:product_update' object.pk %}>edit</a>
            </button>
        </p>
        <p>
            <button>
                <a href={% url 'admin:product_delete' object.pk %}>delete</a>
            </button>
        </p>
        <p>
            <button>
                <a href={% url 'admin:products' object.category.pk %}>back</a>
            </button>
        </p>
    </div>
    <div class="product_desc">
        <b>Author</b>
        <p>{{ object.artist }}</p><br><br>
        <b>Description</b>
        <p>{{ object.description }}</p>
    </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="new_category_form">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="save">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:products' category.pk %}">
            to art objects list
        </a>
    </button>
</div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load humanize %}
{% load static %}


{% block content %}
<div class="products_list">
    <button class="new_product">
        <a href={% url 'admin:product_create' category.pk %}>New product</a>
    </button>

    {% for object in objects %}
    <div class="product_record">
        <img src="{{ media_url }}{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <button>
                <a href={% url 'admin:product_read' object.pk %}>More info</a>
            </button>
            <button>
                <a href={% url 'admin:product_update' object.pk %}>Edit</a>
            </button>
            <button>
                <a href={% url 'admin:product_delete' object.pk %}>Delete</a>
            </button>
        </div>
        <div class="summary">
            <b>Price</b>
            <p>{{ object.price|stringformat:"d"|intcomma }} $</p>
            <b>Quantity</b>
            <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
            {{ object.short_desc|title }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="user_delete">
    Are you sure you want to delete {{ object.username }} {% if object.first_name %}
    ({{ object.first_name|title }}</b>
    {% if object.last_name %}
    {{ object.last_name|title }}
    {% endif %})
    {% endif %}?
    <form action="{% url 'admin:user_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="delete">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin:users' %}">cancel</a>
    </button>
</div>
{% endblock content %}

adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="save">
</form>
<button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' %}">
        to users list
    </a>
</button>
{% endblock content %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
<div class="users_list">
    <button class="new_user">
        <a href={% url 'admin:user_create' %}>New user</a>
    </button>
    {% for object in object_list %}
    <div class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img src="{{ media_url }}{{ object.avatar|default:'users_avatars/Koala.jpg' }}" alt="{{ object.username }}">
        <div class="user_role">
            {% if object.is_superuser %}Administrator{% else %}User{% endif %}
            <button>
                <a href={% url 'admin:user_update' object.pk %}>Edit</a>
            </button>
            <button>
                <a href={% url 'admin:user_delete' object.pk %}>Delete</a>
            </button>
        </div>
        <div class="user_name">
            <p>
                <strong>{{ object.username }}</strong>
            </p>
            <p>
                {% if object.first_name %}
                <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                <p>{{ object.last_name|title }}</p>
                {% endif %}
                {% endif %}
            </p>
        </div>
        <div class="user_age">
            age:<br>
            {{ object.age }} years
        </div>
        <div class="user_email">
            email:<br>
            {{ object.email }}
        </div>
        <div class="user_lastlogin">
            logged:<br>
            {{ object.last_login }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}