artshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

from .apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    path("", basketapp.basket, name="view"),
    path("add/<int:pk>/", basketapp.basket_add, name="add"),
    path("remove/<int:pk>/", basketapp.basket_remove, name="remove"),
    path("edit/<int:pk>/<int:quantity>/", basketapp.basket_edit, name="edit"),
]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", mainapp.products, name="index"),
    path("products/<int:pk>/", mainapp.products, name="products"),
    path("products/<int:pk>/page/<int:page>", mainapp.products, name="page"),
    path("product/<int:pk>/", mainapp.product, name="product"),
    path('catalog/', mainapp.catalog, name='catalog'),
    path('contacts/', mainapp.contacts, name='contacts'),
]

mainapp/models.py
from django.db import models

# Create your models here.
class ArtCategory(models.Model):
    name = models.CharField(verbose_name="name", max_length=64, unique=True)
    description = models.TextField(verbose_name="description", blank=True)
    is_active = models.BooleanField(verbose_name="category is active", default=True)

    def __str__(self):
        return self.name

class ArtObject(models.Model):
    category = models.ForeignKey(ArtCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="artobject name", max_length=128)
    image = models.ImageField(upload_to="art_images", blank=True)
    artist = models.CharField(verbose_name="author", max_length=60, blank=True)
    description = models.TextField(verbose_name="artobject description", blank=True)
    price = models.DecimalField(verbose_name="price", max_digits=12, decimal_places=2, default=0)
    location = models.CharField(verbose_name="location", max_length=128)
    is_active = models.BooleanField(verbose_name="art object is active", default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="phone number")
    email = models.EmailField(max_length=254, verbose_name="email")
    city = models.CharField(max_length=128, verbose_name="city")
    address = models.CharField(max_length=254, verbose_name="address")

    def __str__(self):
        return f"{self.pk} {self.email}"
    

mainapp/views.py
from django.conf import settings
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
import datetime
from .models import Contact, ArtObject, ArtCategory
from basketapp.models import Basket
import random

# Create your views here.

def main(request):
    title = "главная",
    
    content = {"title": title}
    return render(request, "mainapp/index.html", content)

def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []

def get_hot_product():
    products = ArtObject.objects.filter(is_active=True, category__is_active=True)
    return random.sample(list(products), 1)[0]

def products(request, pk=None, page=1):
    title = "Картины"

    basket = get_basket(request.user)
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    if pk is not None:
        if pk == 0:
            products = ArtObject.objects.filter(is_active=True, category__is_active=True).order_by("price")
            category = {"pk": 0, "name": "all"}
        else:
            category = get_object_or_404(ArtCategory, pk=pk)
            products = ArtObject.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by("price")
        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)    
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        content = {
            "title": title, 
            "products": products_paginator, 
            "category": category, 
            "media_url": settings.MEDIA_URL,
            "basket": basket,
            }
        return render(request, "mainapp/products_list.html", content)
    products = ArtObject.objects.filter(is_active=True, category__is_active=True)[:3]
    content = {
        "title": title,
        "products": products,
        "media_url": settings.MEDIA_URL,
        "basket": basket,
    }
    if pk:
        print(f"User select category: {pk}")
    return render(request, "mainapp/products.html", content)

def contacts(request):
    title = "о нас"
    visit_date = timezone.now()
    locations = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "locations": locations}
    return render(request, "mainapp/contacts.html", content)

def catalog(request):
    title = "Каталог"
    links_menu = ArtCategory.objects.all()
    basket = get_basket(request.user)
    hot_product = get_hot_product()
    content = {
        "title": title, 
        "links_menu": links_menu,
        "hot_product": hot_product,
        "media_url": settings.MEDIA_URL,
        "basket": basket,
        }
    return render(request, "mainapp/catalog.html", content)

def product(request, pk):
    title = "продукты"
    content = {
        "title": title,
        "product": get_object_or_404(ArtObject, pk=pk),
        "basket": get_basket(request.user),
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/product.html", content)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %} 
        {{ title}} 
      {% endblock title %}
    </title>
    {% block css %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}" />
    {% endblock css %}
  </head>
  <body>
    <div class="container">
      {% block header1 %}
      {% include 'mainapp/includes/inc_header1.html' %}
      {% endblock header1 %} 
      
      {% block header2 %}
      
      {% include 'mainapp/includes/inc_header2.html' %}

      {% endblock header2 %} 
      {% block content %} {% endblock content %}
  
    <div class="clr"></div>
    {% block footer %}
    <div class="footer">
      <div class="networks">
        <ul>
          <li>
            <a href="#"><i class="fab fa-facebook-f"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-twitter"></i></a>
          </li>
          <li>
            <a href="#"><i class="fas fa-rss"></i></a>
          </li>
          <li>
            <a href="#"><i class="fab fa-vk"></i></a>
          </li>
        </ul>
      </div>
      <small>Все права защищены &copy; 2020</small>
    </div>
    {% endblock footer %}
  </div>
  </body>
</html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
  <div class="mainpage">
  <div class="inc-cat-menu">
    {% include 'mainapp/includes/inc_categories_menu.html' %}
  </div>
    <div class="hot-product">
    <h3 class="red">HOT DEAL!</h3>
    <h3 class="big-bold">{{ hot_product.name }}</h3>
    <img src="{{ media_url }}{{ hot_product.image }}" alt="{{ hot_product.artist }}">
    <p>Category: {{ hot_product.category.name }}</p>
    <p>Price: {{ hot_product.price|stringformat:"d"|intcomma }} $</p>
          <a href="{% url 'basket:add' hot_product.pk %}">
            <button class="button-basket">
              Add to basket
            </button>
        </a>
    </div>
  </div>

  
{% endblock content %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static mail_to %}

{% block content %}
  <div class="mainpage">
    <h1>Today is: {{ visit_date|date:"l, j F, Y" }}</h1><br>

    <h4>You can contact us by following e-mails:
    <li>
    {% for location in locations %}
    <ol>
    {{ location.email|mail_to }}
    </ol>
    {% endfor %}
    </ul>
    </h4>
    <br>
    <h5>Our site is under development. Sorry for your inconvenience.</h5>

</div>
  {% endblock content %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %} 
{% load static %}

  {% block content %}
  <div class="mainpage-index">
  <div class="about">
    <h1>FLAME ART</h1>
  </div>
</div>
  {% endblock content %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
  <div class="mainpage">
    <div class="tab-content">
      <div class="block">
        <a href="{{ product.image }}"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.artist }}">
        </a>
        <div class="product-text">
          <h4>{{ product.name }}</h4>
          <p>{{ product.artist }}</p>
          <p>Category: {{ product.category.name }}</p>
          <p>Price: {{ product.price|stringformat:"d"|intcomma }} $</p>
          <p>Description: {{ product.description }}</p>
          <a href="{% url 'basket:add' product.pk %}">
            <button class="button-basket">
              Add to basket
            </button>
        </a>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/product_list.html
{% extends 'mainapp/products.html' %}
{% load static %}
{% load humanize %}

{% block content %}
  <div class="mainpage">
  <div class="title clearfix">
            <h2>
                Category: "{{ category.name: title }}"
            </h2>
        </div>
    <div class="tab-content clearfix">
    {% for product in products %}
      <div class="block">
        <a href="#"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.artist }}">
        </a>
        <div class="product-text">
          <h4>{{ product.name }}</h4>
          <p>{{ product.artist }}</p>
          <p>Category: {{ product.category.name }}</p>
          <p>Price: {{ product.price|stringformat:"d"|intcomma }} $</p>
        </div>
      </div>
      {% endfor %}
    </div>
</div>
<div class="clr"></div>
{% endblock content %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
  <div class="mainpage">
    <div class="paginator">
                {% if products.has_previous %}
                <a href="{% url 'products:page' category.pk products.previous_page_number %}"><i
                        class="fas fa-chevron-circle-left"></i></a>
                {% endif %}
                <span class="current">
                    page {{ products.number }} from {{ products.paginator.num_pages }}
                </span>
                {% if products.has_next %}
                <a href="{% url 'products:page' category.pk products.next_page_number %}"><i
                        class="fas fa-chevron-circle-right"></i></a>
                {% endif %}
            </div>
    <div class="tab-content">
      {% for product in products %}
      <div class="block">
        <a href="{% url 'products:product' product.pk %}"><img src="{{ media_url }}{{ product.image }}" alt="{{ product.artist }}">
        </a>
        <div class="product-text">
          <h4>{{ product.name }}</h4>
          <p>{{ product.artist }}</p>
          <p>Category: {{ product.category.name }}</p>
          <p>Price: {{ product.price|stringformat:"d"|intcomma }} $</p>
          <a href="{% url 'basket:add' product.pk %}">
            <button class="button-basket">
              Add to basket
            </button>
        </a>
        </div>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/products.html' %}
{% load static uppercase %}
{% load humanize %}

{% block content %}
  <div class="mainpage">
  <div class="title clearfix">
            <h2>
                Category: "{{ category.name|title }}"
            </h2>
        </div>
    <div class="paginator">
                {% if products.has_previous %}
                <a href="{% url 'products:page' category.pk products.previous_page_number %}"><i
                        class="fas fa-chevron-circle-left"></i></a>
                {% endif %}
                <span class="current">
                    page {{ products.number }} from {{ products.paginator.num_pages }}
                </span>
                {% if products.has_next %}
                <a href="{% url 'products:page' category.pk products.next_page_number %}"><i
                        class="fas fa-chevron-circle-right"></i></a>
                {% endif %}
            </div>
    <div class="tab-content clearfix">
    {% for product in products %}
      <div class="block">
        <a href={% url 'products:product' product.pk %}><img src="{{ media_url }}{{ product.image }}" alt="{{ product.artist }}">
        </a>
        <div class="product-text">
          <h4>{{ product.name }}</h4>
          <p>{{ product.artist }}</p>
          <p>Category: {{ product.category.name|uppercase }}</p>
          <p>Price: {{ product.price|stringformat:"d"|intcomma }} $</p>
          <a href="{% url 'basket:add' product.pk %}">
            <button class="button-basket">
              Add to basket
            </button>
        </a>
        </div>
      </div>
      {% endfor %}
    </div>
</div>
<div class="clr"></div>
{% endblock content %}